In [6]:
import numpy as np
import rioxarray
from rasterio.enums import Resampling
from osgeo import gdal

In [7]:
mds_file = 'data/raster/MDS_sampa-ZSTD.tif'
mds_file_20 = 'data/raster/MDS_sampa-ZSTD-20m.tif'

In [8]:
ds = gdal.Translate(mds_file_20, mds_file, xRes=20, yRes=20, resampleAlg="average", format='GTiff',  multithread=True)

In [5]:
ds.

<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x7f4f25f87b70> >

In [6]:
mds = rioxarray.open_rasterio('data/raster/MDS_sampa-ZSTD.tif', chunks=1000, lock=False)

In [7]:
mds

<xarray.DataArray (band: 1, y: 146905, x: 96008)>
dask.array<open_rasterio-8f9874533ced06e14aedc54a6de25de8<this-array>, shape=(1, 146905, 96008), dtype=float32, chunksize=(1, 1000, 1000), chunktype=numpy.ndarray>
Coordinates:
  * band         (band) int64 1
  * x            (x) float64 3.129e+05 3.129e+05 ... 3.609e+05 3.609e+05
  * y            (y) float64 7.417e+06 7.417e+06 ... 7.343e+06 7.343e+06
    spatial_ref  int64 0
Attributes:
    COLOR_TABLE_RULES_COUNT:   121
    COLOR_TABLE_RULE_RGB_0:    -1.368651e+03 1.442370e+02 37 57 175 37 57 176
    COLOR_TABLE_RULE_RGB_1:    1.442370e+02 1.512249e+02 37 57 176 37 58 176
    COLOR_TABLE_RULE_RGB_10:   6.124286e+02 6.543562e+02 37 62 180 37 62 181
    COLOR_TABLE_RULE_RGB_100:  1.017729e+03 1.024717e+03 255 246 240 255 247 241
    COLOR_TABLE_RULE_RGB_101:  1.024717e+03 1.031705e+03 255 247 241 255 247 242
    COLOR_TABLE_RULE_RGB_102:  1.031705e+03 1.035199e+03 255 247 242 255 248 242
    COLOR_TABLE_RULE_RGB_103:  1.035199e+03 1.038693e+03 255 248 242 255 248 243
    COLOR_TABLE_RULE_RGB_104:  1.038693e+03 1.045680e+03 255 248 243 255 248 244
    COLOR_TABLE_RULE_RGB_105:  1.045680e+03 1.049174e+03 255 248 244 255 249 244
    COLOR_TABLE_RULE_RGB_106:  1.049174e+03 1.052668e+03 255 249 244 255 249 245
    COLOR_TABLE_RULE_RGB_107:  1.052668e+03 1.059656e+03 255 249 245 255 249 246
    COLOR_TABLE_RULE_RGB_108:  1.059656e+03 1.063150e+03 255 249 246 255 250 246
    COLOR_TABLE_RULE_RGB_109:  1.063150e+03 1.066644e+03 255 250 246 255 250 247
    COLOR_TABLE_RULE_RGB_11:   6.543562e+02 6.858019e+02 37 62 181 37 63 181
    COLOR_TABLE_RULE_RGB_110:  1.066644e+03 1.077126e+03 255 250 247 255 251 248
    COLOR_TABLE_RULE_RGB_111:  1.077126e+03 1.087608e+03 255 251 248 255 251 249
    COLOR_TABLE_RULE_RGB_112:  1.087608e+03 1.094596e+03 255 251 249 255 252 249
    COLOR_TABLE_RULE_RGB_113:  1.094596e+03 1.098090e+03 255 252 249 255 252 250
    COLOR_TABLE_RULE_RGB_114:  1.098090e+03 1.108572e+03 255 252 250 255 252 251
    COLOR_TABLE_RULE_RGB_115:  1.108572e+03 1.115560e+03 255 252 251 255 253 251
    COLOR_TABLE_RULE_RGB_116:  1.115560e+03 1.122548e+03 255 253 251 255 253 252
    COLOR_TABLE_RULE_RGB_117:  1.122548e+03 1.136524e+03 255 253 252 255 253 253
    COLOR_TABLE_RULE_RGB_118:  1.136524e+03 1.143512e+03 255 253 253 255 254 253
    COLOR_TABLE_RULE_RGB_119:  1.143512e+03 1.164475e+03 255 254 253 255 254 254
    COLOR_TABLE_RULE_RGB_12:   6.858019e+02 6.997777e+02 37 63 181 37 63 182
    COLOR_TABLE_RULE_RGB_120:  1.164475e+03 2.125316e+03 255 254 254 255 254 254
    COLOR_TABLE_RULE_RGB_13:   6.997777e+02 7.067657e+02 37 63 182 37 64 182
    COLOR_TABLE_RULE_RGB_14:   7.067657e+02 7.102596e+02 37 64 182 37 64 183
    COLOR_TABLE_RULE_RGB_15:   7.102596e+02 7.137536e+02 37 64 183 37 65 183
    COLOR_TABLE_RULE_RGB_16:   7.137536e+02 7.172476e+02 37 65 183 37 66 185
    COLOR_TABLE_RULE_RGB_17:   7.172476e+02 7.207415e+02 37 66 185 37 69 188
    COLOR_TABLE_RULE_RGB_18:   7.207415e+02 7.242355e+02 37 69 188 37 80 199
    COLOR_TABLE_RULE_RGB_19:   7.242355e+02 7.277295e+02 37 80 199 38 93 214
    COLOR_TABLE_RULE_RGB_2:    1.512249e+02 2.385741e+02 37 58 176 37 58 177
    COLOR_TABLE_RULE_RGB_20:   7.277295e+02 7.312234e+02 38 93 214 39 109 231
    COLOR_TABLE_RULE_RGB_21:   7.312234e+02 7.347174e+02 39 109 231 39 125 249
    COLOR_TABLE_RULE_RGB_22:   7.347174e+02 7.382114e+02 39 125 249 43 152 252
    COLOR_TABLE_RULE_RGB_23:   7.382114e+02 7.417053e+02 43 152 252 46 168 253
    COLOR_TABLE_RULE_RGB_24:   7.417053e+02 7.451993e+02 46 168 253 49 184 254
    COLOR_TABLE_RULE_RGB_25:   7.451993e+02 7.486933e+02 49 184 254 72 207 255
    COLOR_TABLE_RULE_RGB_26:   7.486933e+02 7.521872e+02 72 207 255 89 221 255
    COLOR_TABLE_RULE_RGB_27:   7.521872e+02 7.556812e+02 89 221 255 106 235 253
    COLOR_TABLE_RULE_RGB_28:   7.556812e+02 7.591752e+02 106 235 253 117 235 225
    COLOR_TABLE_RULE_RGB_29:   7.591752e+02 7.626691e+02 117 235 225 129 235 197
    COLOR_TABLE_RULE_RGB_3

In [41]:
mds_std = 60 # 3 X o STD parece um bom chute para SP

In [42]:
max_horizontal_distance = 10000
max_vertical_distance = 3 * mds_std
thetas = 40
phis = 8
delta_theta = 2*np.pi/thetas
resolution = 0.5
phis_angles = np.arcsin(np.arange(1/phis/2 + 1/phis, 1, 1/phis))
tangents = 1/np.tan(phis_angles) #CoTangente
# indices = np.indices(xds.rio.shape)

In [26]:
pad_max_meters = np.ceil((tangents[::-1] * max_vertical_distance))
pad_max_meters

array([ 67., 130., 191., 265., 370., 548., 943.])

In [35]:
downscales = np.floor(tangents[::-1])
downscales = np.where(downscales == 0, 1, downscales)
downscales

array([1., 1., 1., 1., 2., 3., 5.])

In [38]:
pad_max_meters / downscales

array([ 67.        , 130.        , 191.        , 265.        ,
       185.        , 182.66666667, 188.6       ])

In [11]:
np.rad2deg(phis_angles)

array([10.80692287, 18.20995686, 25.94447977, 34.22886633, 43.43253656,
       54.3409123 , 69.63586519])