In [82]:
import numpy as np

In [83]:
max_horizontal_distance = 10000
max_vertical_distance = 1000 #Precisa ser menor que max_horizontal_distance
thetas = 40
phis = 8
delta_theta = 2*np.pi/thetas
resolution = 0.5
phis_angles = np.arcsin(np.arange(1/phis/2 + 1/phis, 1, 1/phis))
tangents = np.tan(np.pi/2 - phis_angles)
# indices = np.indices(xds.rio.shape)

In [85]:
## Aqui --<-->--
## Resampling rates downscale
np.floor((tangents[::-1] * 1000) * np.pi * 2 / thetas * resolution * (np.sqrt(2) / 2))

array([ 20.,  39.,  58.,  81., 114., 168., 290.])

In [66]:
np.rad2deg(phis_angles[::-1])

array([69.63586519, 54.3409123 , 43.43253656, 34.22886633, 25.94447977,
       18.20995686, 10.80692287])

In [63]:
1000 / np.tan(phis_angles[::-1])

array([ 371.18429086,  717.49069639, 1056.26818533, 1469.86183948,
       2055.35636713, 3039.73683071, 5238.7445485 ])