In [1]:
from svfpy import svfpy
import numpy as np

In [2]:
mds = '/media/fernando/DATA/nyc_lidar/results/DSM/all-DSM-NYC.tiff'

In [3]:
svf = svfpy.SVF(mds, '/media/fernando/DATA/svf-nyc/', kernel_size_side=2500, tmp_folder='/media/fernando/DATA/svf-nyc/', max_vertical_difference=600, boundary='test/data/nyc-boundary.gpkg')

In [4]:
svf.downscales()

array([ 1.,  1.,  2.,  2.,  4.,  6., 10., 31.])

In [5]:
svf.resolutions

array([ 0.5,  1. ,  2. ,  3. ,  5. , 15.5])

In [6]:
svf.pad_max()

array([1056, 1558, 1283, 1583, 1263, 1252, 1277, 1600], dtype=int16)

In [7]:
svf.prepare_downscales()

Preparing Downscale, resolution of 0.5
Preparing Downscale, resolution of 1.0
Preparing Downscale, resolution of 2.0
Preparing Downscale, resolution of 3.0
Preparing Downscale, resolution of 5.0
Preparing Downscale, resolution of 15.5


[<xarray.DataArray (band: 1, y: 315000, x: 315000)>
 [99225000000 values with dtype=float32]
 Coordinates:
   * band         (band) int64 1
   * x            (x) float64 9.125e+05 9.125e+05 9.125e+05 ... 1.07e+06 1.07e+06
   * y            (y) float64 2.75e+05 2.75e+05 2.75e+05 ... 1.175e+05 1.175e+05
     spatial_ref  int64 0
 Attributes:
     _FillValue:    -9999.0
     scale_factor:  1.0
     add_offset:    0.0,
 <xarray.DataArray (band: 1, y: 157500, x: 157500)>
 [24806250000 values with dtype=float32]
 Coordinates:
   * band         (band) int64 1
   * x            (x) float64 9.125e+05 9.125e+05 9.125e+05 ... 1.07e+06 1.07e+06
   * y            (y) float64 2.75e+05 2.75e+05 2.75e+05 ... 1.175e+05 1.175e+05
     spatial_ref  int64 0
 Attributes:
     _FillValue:    -9999.0
     scale_factor:  1.0
     add_offset:    0.0,
 <xarray.DataArray (band: 1, y: 78750, x: 78750)>
 [6201562500 values with dtype=float32]
 Coordinates:
   * band         (band) int64 1
   * x            (x) flo

In [8]:
svf.svf()

3 79 0.5
3 80 0.5
3 81 0.5
