In [1]:
from svfpy import svfpy
import numpy as np

In [2]:
mds = '/media/fernando/DATA/nyc_lidar/results/DSM/all-DSM-NYC.tiff'

In [3]:
svf = svfpy.SVF(
    mds, '/media/fernando/DATA/svf-nyc/', 
    multiplier=0.3048,
    kernel_size_side=800, 
    tmp_folder='/media/fernando/DATA/svf-nyc/', 
    max_vertical_difference=1200, 
    boundary='test/data/nyc-boundary.gpkg',
    unit = 'ft'
)

In [4]:
svf.downscales()

array([ 1.,  1.,  2.,  3.,  5.,  7., 13., 41.])

In [5]:
svf.downscales()

array([ 1.,  1.,  2.,  3.,  5.,  7., 13., 41.])

In [6]:
svf.resolutions

array([ 1.25,  2.5 ,  3.75,  6.25,  8.75, 16.25, 51.25])

In [7]:
svf.resolutions[1:]

array([ 2.5 ,  3.75,  6.25,  8.75, 16.25, 51.25])

In [8]:
svf.pad_max()

array([1242, 2245, 1696, 1586, 1357, 1424, 1334, 1295], dtype=int16)

In [9]:
svf.prepare_downscales()

Preparing Downscale, resolution of 1.25
Preparing Downscale, resolution of 2.5
Preparing Downscale, resolution of 3.75
Preparing Downscale, resolution of 6.25
Preparing Downscale, resolution of 8.75
Preparing Downscale, resolution of 16.25
Preparing Downscale, resolution of 51.25


[<xarray.DataArray (band: 1, y: 126000, x: 126000)>
 [15876000000 values with dtype=float32]
 Coordinates:
   * band         (band) int64 1
   * x            (x) float64 9.125e+05 9.125e+05 9.125e+05 ... 1.07e+06 1.07e+06
   * y            (y) float64 2.75e+05 2.75e+05 2.75e+05 ... 1.175e+05 1.175e+05
     spatial_ref  int64 0
 Attributes:
     _FillValue:    -9999.0
     scale_factor:  1.0
     add_offset:    0.0,
 <xarray.DataArray (band: 1, y: 63000, x: 63000)>
 [3969000000 values with dtype=float32]
 Coordinates:
   * band         (band) int64 1
   * x            (x) float64 9.125e+05 9.125e+05 9.125e+05 ... 1.07e+06 1.07e+06
   * y            (y) float64 2.75e+05 2.75e+05 2.75e+05 ... 1.175e+05 1.175e+05
     spatial_ref  int64 0
 Attributes:
     _FillValue:    -9999.0
     scale_factor:  1.0
     add_offset:    0.0,
 <xarray.DataArray (band: 1, y: 42000, x: 42000)>
 [1764000000 values with dtype=float32]
 Coordinates:
   * band         (band) int64 1
   * x            (x) float6

In [ ]:
svf.svf()

In [10]:
svf._agg_all()

'gdal_calc.py -A /media/fernando/DATA/svf-nyc/all_1.25_upscaled_1.25.tiff -B /media/fernando/DATA/svf-nyc/all_2.5_upscaled_1.25.tiff -C /media/fernando/DATA/svf-nyc/all_3.75_upscaled_1.25.tiff -D /media/fernando/DATA/svf-nyc/all_6.25_upscaled_1.25.tiff -E /media/fernando/DATA/svf-nyc/all_8.75_upscaled_1.25.tiff -F /media/fernando/DATA/svf-nyc/all_16.25_upscaled_1.25.tiff -G /media/fernando/DATA/svf-nyc/all_51.25_upscaled_1.25.tiff --outfile=svf_all.tiff --calc="A+B+C+D+E+F+G" --quiet --overwrite --hideNoData --NoDataValue=-9999 --co="COMPRESS=ZSTD" --co="PREDICTOR=3" --co="BIGTIFF=YES" --extent=intersect'

In [17]:
np.rad2deg(np.pi/2 - svf.phis_angles)

array([86.4166783 , 79.19307713, 71.79004314, 64.05552023, 55.77113367,
       46.56746344, 35.6590877 , 20.36413481])

In [12]:
svf.phis_angles

array([0.06254076, 0.18861639, 0.3178237 , 0.45281659, 0.59740642,
       0.75804077, 0.94842784, 1.21537513])

In [20]:
svf.downscales()

array([ 1.,  1.,  2.,  2.,  4.,  6., 10., 31.])