In [1]:
from svfpy import svfpy
import numpy as np

In [2]:
mds = '/media/fernando/DATA/nyc_lidar/results/DSM/all-DSM-NYC.tiff'

In [3]:
svf = svfpy.SVF(
    mds, '/media/fernando/DATA/svf-nyc/', 
    kernel_size_side=2500, 
    tmp_folder='/media/fernando/DATA/svf-nyc/', 
    max_vertical_difference=600, 
    boundary='test/data/nyc-boundary.gpkg'
)

In [4]:
svf.downscales()

array([ 1.,  1.,  2.,  2.,  4.,  6., 10., 31.])

In [5]:
svf.resolutions

array([ 0.5,  1. ,  2. ,  3. ,  5. , 15.5])

In [6]:
svf.resolutions[1:]

array([ 1. ,  2. ,  3. ,  5. , 15.5])

In [7]:
svf.pad_max()

array([1056, 1558, 1283, 1583, 1263, 1252, 1277, 1600], dtype=int16)

In [8]:
svf.prepare_downscales()

Preparing Downscale, resolution of 0.5
Preparing Downscale, resolution of 1.0
Preparing Downscale, resolution of 2.0
Preparing Downscale, resolution of 3.0
Preparing Downscale, resolution of 5.0
Preparing Downscale, resolution of 15.5


[<xarray.DataArray (band: 1, y: 315000, x: 315000)>
 [99225000000 values with dtype=float32]
 Coordinates:
   * band         (band) int64 1
   * x            (x) float64 9.125e+05 9.125e+05 9.125e+05 ... 1.07e+06 1.07e+06
   * y            (y) float64 2.75e+05 2.75e+05 2.75e+05 ... 1.175e+05 1.175e+05
     spatial_ref  int64 0
 Attributes:
     _FillValue:    -9999.0
     scale_factor:  1.0
     add_offset:    0.0,
 <xarray.DataArray (band: 1, y: 157500, x: 157500)>
 [24806250000 values with dtype=float32]
 Coordinates:
   * band         (band) int64 1
   * x            (x) float64 9.125e+05 9.125e+05 9.125e+05 ... 1.07e+06 1.07e+06
   * y            (y) float64 2.75e+05 2.75e+05 2.75e+05 ... 1.175e+05 1.175e+05
     spatial_ref  int64 0
 Attributes:
     _FillValue:    -9999.0
     scale_factor:  1.0
     add_offset:    0.0,
 <xarray.DataArray (band: 1, y: 78750, x: 78750)>
 [6201562500 values with dtype=float32]
 Coordinates:
   * band         (band) int64 1
   * x            (x) flo

In [9]:
svf.svf()

Agregando 0.5
0...10...20...30...40...50...60...70...80...90...100 - done.


Warning 1: Computed -srcwin 0 -0 315000 315000 falls partially outside raster extent. Going on however.


Input file size is 312500, 312500
0...10...20...30...40...50...60...70...80...90...100 - done.
Agregando 1.0
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 157500, 157500
0...10...20...30...40...50...60...70...80...90...100 - done.
Agregando 2.0
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 80000, 80000
0...10...20...30...40...50...60...70...80...90...100 - done.
Agregando 3.0
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 52500, 52500
0...10...20...30...40...50...60...70...80...90...100 - done.
Agregando 5.0
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 32500, 32500
0...10...20...30...40...50...60...70...80...90...100 - done.
Agregando 15.5
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 12500, 12500
0...10...20...30...40...50...60...70...80...90...100 - done.


In [17]:
np.rad2deg(np.pi/2 - svf.phis_angles)

array([86.4166783 , 79.19307713, 71.79004314, 64.05552023, 55.77113367,
       46.56746344, 35.6590877 , 20.36413481])

In [12]:
svf.phis_angles

array([0.06254076, 0.18861639, 0.3178237 , 0.45281659, 0.59740642,
       0.75804077, 0.94842784, 1.21537513])

In [20]:
svf.downscales()

array([ 1.,  1.,  2.,  2.,  4.,  6., 10., 31.])