In [1]:
from svfpy import svfpy
import numpy as np

In [2]:
mds = '/media/fernando/DATA/nyc_lidar/results/DSM/all-DSM-NYC.tiff'

In [3]:
svf = svfpy.SVF(mds, '/media/fernando/DATA/svf-nyc/', kernel_size_side=2500, tmp_folder='/media/fernando/DATA/svf-nyc/', max_vertical_difference=600)

In [4]:
svf.downscales()

array([ 1.,  1.,  2.,  2.,  4.,  6., 10., 31.])

In [5]:
svf.resolutions

array([ 0.5,  1. ,  2. ,  3. ,  5. , 15.5])

In [6]:
svf.pad_max()

array([1056, 1558, 1283, 1583, 1263, 1252, 1277, 1600], dtype=int16)

In [7]:
svf.prepare_downscales()

Preparing Downscale, resolution of 0.5
Preparing Downscale, resolution of 1.0
Usage: gdal_translate [--help-general] [--long-usage]
       [-ot {Byte/Int16/UInt16/UInt32/Int32/Float32/Float64/
             CInt16/CInt32/CFloat32/CFloat64}] [-strict]
       [-if format]* [-of format]
       [-b band] [-mask band] [-expand {gray|rgb|rgba}]
       [-outsize xsize[%]|0 ysize[%]|0] [-tr xres yres]
       [-r {nearest,bilinear,cubic,cubicspline,lanczos,average,mode}]
       [-unscale] [-scale[_bn] [src_min src_max [dst_min dst_max]]]* [-exponent[_bn] exp_val]*
       [-srcwin xoff yoff xsize ysize] [-epo] [-eco]
       [-projwin ulx uly lrx lry] [-projwin_srs srs_def]
       [-a_srs srs_def] [-a_coord_epoch epoch]
       [-a_ullr ulx uly lrx lry] [-a_nodata value]
       [-a_scale value] [-a_offset value]
       [-nogcp] [-gcp pixel line easting northing [elevation]]*
       |-colorinterp{_bn} {red|green|blue|alpha|gray|undefined}]
       |-colorinterp {red|green|blue|alpha|gray|undefined},.

ERROR 6: Unknown option name '-overwrite'


RasterioIOError: /media/fernando/DATA/svf-nyc/all-DSM-NYC_100cm_.tif: No such file or directory

In [8]:
svf.svf()

Agregando 0.5
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 95000, 147500
0...10...20...30...40...50...60...70...80...90...100 - done.
Agregando 1.0
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 47500, 75000
0...10...20...30...40...50...60...70...80...90...100 - done.
Agregando 2.0
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 25000, 37500
0...10...20...30...40...50...60...70...80...90...100 - done.
Agregando 3.0
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 17500, 25000
0...10...20...30...40...50...60...70...80...90...100 - done.
Agregando 5.0
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 10000, 15000
0...10...20...30...40...50...60...70...80...90...100 - done.
Agregando 15.5
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 5000, 5000
0...10...20...30...40...50...60...70...80...90...100 