In [83]:
import rioxarray
import numpy as np
import cv2 as cv
from scipy.ndimage import rotate

In [2]:
file = 'test/data/mds_sao_paulo_city_1000.tiff'

In [3]:
xds = rioxarray.open_rasterio(file)

In [4]:
xds.rio.width, xds.rio.height

(1000, 1000)

In [5]:
a = np.random.randint(0, 16, (4,4))

In [6]:
a

array([[ 3,  2,  8, 15],
       [14, 14,  8, 12],
       [12, 10,  6,  5],
       [ 6,  8,  0, 13]])

In [92]:
c = np.arange(144).reshape(12, 12)

In [93]:
c

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131],
       [132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143]])

In [95]:
rotate(c, 15, reshape=False)

array([[  0,   0,   0,   0,   0,   7,   9,  14,  19,  24,   0,   0],
       [  0,   0,   4,   8,  13,  19,  23,  27,  31,  35,   0,   0],
       [  8,  13,  18,  22,  26,  30,  34,  38,  42,  46,  50,   0],
       [ 21,  25,  29,  33,  37,  41,  45,  49,  53,  57,  62,   0],
       [ 32,  36,  40,  44,  48,  52,  57,  61,  65,  69,  73,   0],
       [ 43,  48,  52,  56,  60,  64,  68,  72,  76,  80,  84,  88],
       [ 55,  59,  63,  67,  71,  75,  79,  83,  87,  91,  95, 100],
       [  0,  70,  74,  78,  82,  86,  91,  95,  99, 103, 107, 111],
       [  0,  81,  86,  90,  94,  98, 102, 106, 110, 114, 118, 122],
       [  0,  93,  97, 101, 105, 109, 113, 117, 121, 125, 130, 135],
       [  0,   0, 108, 112, 116, 120, 124, 130, 135, 139,   0,   0],
       [  0,   0, 119, 124, 129, 134, 136,   0,   0,   0,   0,   0]])

In [81]:
M = cv.getRotationMatrix2D((1.5,1.5), 15, 1)
rotated = cv.warpAffine(c, M, (4, 4))

In [82]:
rotated

array([[ 0.28710938,  1.3183594 ,  3.125     ,  3.1171875 ],
       [ 2.6875    ,  4.65625   ,  6.75      ,  7.8164062 ],
       [ 5.9765625 ,  8.25      , 10.34375   , 12.3125    ],
       [ 6.7265625 , 11.875     , 12.319336  ,  9.556641  ]],
      dtype=float32)

In [49]:
M

array([[ 0.99990605,  0.01370735, -0.05445362],
       [-0.01370735,  0.99990605,  0.05520522]])

In [7]:
np.maximum.accumulate(a, axis=1)

array([[ 3,  3,  8, 15],
       [14, 14, 14, 14],
       [12, 12, 12, 12],
       [ 6,  8,  8, 13]])

In [8]:
np.maximum.accumulate(a, axis=0)

array([[ 3,  2,  8, 15],
       [14, 14,  8, 15],
       [14, 14,  8, 15],
       [14, 14,  8, 15]])

In [9]:
np.maximum(np.maximum.accumulate(a, axis=1), np.maximum.accumulate(a, axis=0))

array([[ 3,  3,  8, 15],
       [14, 14, 14, 15],
       [14, 14, 12, 15],
       [14, 14,  8, 15]])

In [10]:
# np.argsort(a, axis=1, kind='stable')#, np.argsort(a, axis=1, kind='stable')
np.less_equal(np.maximum.accumulate(a, axis=1), a)

array([[ True, False,  True,  True],
       [ True,  True, False, False],
       [ True, False, False, False],
       [ True,  True, False,  True]])

In [11]:
np.indices(a.shape)

array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [12]:
np.logical_or(np.less_equal(np.argsort(a, axis=0, kind='stable'), np.indices((4, 4))[0]), 
            np.less_equal(np.argsort(a, axis=1, kind='stable'), np.indices((4, 4))[1]))

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [13]:
np.indices((1000, 1000))

array([[[  0,   0,   0, ...,   0,   0,   0],
        [  1,   1,   1, ...,   1,   1,   1],
        [  2,   2,   2, ...,   2,   2,   2],
        ...,
        [997, 997, 997, ..., 997, 997, 997],
        [998, 998, 998, ..., 998, 998, 998],
        [999, 999, 999, ..., 999, 999, 999]],

       [[  0,   1,   2, ..., 997, 998, 999],
        [  0,   1,   2, ..., 997, 998, 999],
        [  0,   1,   2, ..., 997, 998, 999],
        ...,
        [  0,   1,   2, ..., 997, 998, 999],
        [  0,   1,   2, ..., 997, 998, 999],
        [  0,   1,   2, ..., 997, 998, 999]]])

In [14]:
xds.values.shape

(1, 1000, 1000)

In [15]:
# A distancia de X é Cosseno de Theta * tangente de Phi * Z
# A distancia de Y é Seno de Theta * tangente de Phi * Z
# O item 0,0 é o limite e origem das comparações, independente da sua altura


In [16]:
thetas = 32 # deve ser divisível por 4
phis = 8
delta_theta = 2*np.pi/thetas
resolution = xds.rio.resolution()
tangents = np.tan(np.pi/2 - np.arcsin(np.arange(1 - 1/phis/2, 1/phis/2, -1/phis)))
indices = np.indices(xds.rio.shape)

In [17]:
svf = np.zeros(xds.rio.shape, dtype='int16')
svf_x = np.zeros(xds.rio.shape, dtype='int16')
svf_y = np.zeros(xds.rio.shape, dtype='int16')
grid_max = np.zeros(xds.rio.shape)

In [18]:
for i in np.linspace(0, np.pi/2, thetas, endpoint=False):
# for i in [np.pi*3/2]:
    # Itera sobre cada phi
    print(f'Angulo de {np.rad2deg(i)}')
    for t in tangents:
        factor_x = t * np.cos(i)
        factor_y = t * np.sin(i)
        # print(factor_x, factor_y)
        grid_x_axis_1 = xds.values[0] * factor_x + resolution[0] * indices[1] * np.cos(i) 
        grid_x_axis_1_cum = np.maximum.accumulate(np.abs(grid_x_axis_1), axis=1)
        grid_y_axis_0 = xds.values[0] * factor_y + resolution[0] * indices[0] * np.sin(i)
        grid_y_axis_0_cum = np.maximum.accumulate(np.abs(grid_y_axis_0), axis=0)

        # grid_max_cum = np.maximum(grid_x_axis_1_cum, grid_y_axis_0_cum)

        # x_axis_1_is_visible = np.less_equal(grid_max_cum, np.abs(grid_x_axis_1))
        # y_axis_0_is_visible = np.less_equal(grid_max_cum, np.abs(grid_y_axis_0))

        x_axis_1_is_visible = np.less_equal(grid_x_axis_1_cum, np.abs(grid_x_axis_1))
        y_axis_0_is_visible = np.less_equal(grid_y_axis_0_cum, np.abs(grid_y_axis_0))

        # if np.cos(i) >= 0:
        #     x_axis_1_is_visible = np.less_equal(grid_x_axis_1_cum, grid_x_axis_1)
        # else:
        #     x_axis_1_is_visible = np.less_equal(grid_x_axis_1, indices[1])

        # if np.sin(i) >= 0:
        #     y_axis_0_is_visible = np.less_equal(grid_y_axis_0_cum, grid_y_axis_0)
        # else:
        #     y_axis_0_is_visible = np.less_equal(grid_y_axis_0_cum, grid_y_axis_0)


        svf += np.logical_or(x_axis_1_is_visible, y_axis_0_is_visible)
        svf_x += x_axis_1_is_visible
        svf_y += y_axis_0_is_visible
        # grid_max += grid_max_cum
        # break


Angulo de 0.0
Angulo de 2.8125
Angulo de 5.625
Angulo de 8.4375
Angulo de 11.25
Angulo de 14.0625
Angulo de 16.875
Angulo de 19.6875
Angulo de 22.5
Angulo de 25.3125
Angulo de 28.125
Angulo de 30.937499999999996
Angulo de 33.75
Angulo de 36.5625
Angulo de 39.375
Angulo de 42.1875
Angulo de 45.0
Angulo de 47.8125
Angulo de 50.625
Angulo de 53.4375
Angulo de 56.25
Angulo de 59.0625
Angulo de 61.87499999999999
Angulo de 64.6875
Angulo de 67.5
Angulo de 70.3125
Angulo de 73.125
Angulo de 75.9375
Angulo de 78.75
Angulo de 81.5625
Angulo de 84.375
Angulo de 87.1875


In [19]:
xds.values = svf.reshape(1, 1000, 1000)
xds.rio.to_raster('tmp/result_raytracing.tif')
xds.values = svf_x.reshape(1, 1000, 1000)
xds.rio.to_raster('tmp/result_raytracing_x.tif')
xds.values = svf_y.reshape(1, 1000, 1000)
xds.rio.to_raster('tmp/result_raytracing_y.tif')
# xds.values = grid_max.reshape(1, 1000, 1000)
# xds.rio.to_raster('tmp/result_raytracing_grid_max.tif')


In [33]:
xds.values[0][[0,0],[0,0]]

array([309371.68304443, 309371.68304443])

In [20]:
ccc = np.array([1,50,25,30])

In [21]:
np.indices(ccc.shape) - np.argsort(ccc)

array([[ 0, -1, -1,  2]])

In [22]:
np.indices(ccc.shape)

array([[0, 1, 2, 3]])

In [35]:
b = np.random.randint(0, 100, (10,10))

In [37]:
b

array([[19,  6, 16, 11, 82, 84, 54, 55, 80, 43],
       [26, 46, 50, 32, 85, 37, 95, 16, 74, 59],
       [56, 80, 57, 55, 93, 31, 94, 94, 50, 47],
       [30, 42, 35, 76, 16, 91, 12, 52, 12,  7],
       [20, 43, 98, 88, 97, 32, 43, 58, 60, 91],
       [10, 50, 33,  4,  2, 29, 30, 34, 70, 17],
       [19, 73, 42, 79, 95, 71, 22, 30, 29, 78],
       [86, 66, 20, 62, 84, 81, 30, 29, 52,  5],
       [23, 41, 17, 36, 46, 93, 24, 34,  7,  3],
       [69, 60, 81, 70, 48, 46, 82, 82, 82,  3]])

In [43]:
np.diagonal(b, [0,1,2])

TypeError: 'list' object cannot be interpreted as an integer