In [15]:
import rioxarray
import numpy as np

In [2]:
file = 'test/data/mds_sao_paulo_city_1000.tiff'

In [3]:
xds = rioxarray.open_rasterio(file)

In [7]:
xds.rio.width, xds.rio.height

(1000, 1000)

In [8]:
xds.x

<xarray.DataArray 'x' (x: 1000)>
array([331645.012796, 331645.512796, 331646.012796, ..., 332143.512796,
       332144.012796, 332144.512796])
Coordinates:
  * x            (x) float64 3.316e+05 3.316e+05 ... 3.321e+05 3.321e+05
    spatial_ref  int64 0

In [13]:
xds[0, 213, 321].y

<xarray.DataArray 'y' ()>
array(7391467.15114763)
Coordinates:
    band         int64 1
    x            float64 3.318e+05
    y            float64 7.391e+06
    spatial_ref  int64 0

In [14]:
np.arctan2(xds[0].x

<xarray.DataArray (y: 1000, x: 1000)>
[1000000 values with dtype=float32]
Coordinates:
    band         int64 1
  * x            (x) float64 3.316e+05 3.316e+05 ... 3.321e+05 3.321e+05
  * y            (y) float64 7.392e+06 7.392e+06 ... 7.391e+06 7.391e+06
    spatial_ref  int64 0
Attributes:
    _FillValue:    0.0
    scale_factor:  1.0
    add_offset:    0.0

In [26]:
for i in range(122):
    # print(i)
    xds[0] * np.tan(np.pi/(i+1))

In [19]:
np.tan(np.pi/4)

0.9999999999999999

In [ ]:
# A distancia de X é Cosseno de Theta * tangente de Phi * Z
# A distancia de Y é Seno de Theta * tangente de Phi * Z
# O item 0,0 é o limite e origem das comparações, independente da sua altura


In [31]:
xds.groupby('y')

DataArrayGroupBy, grouped over 'y'
1000 groups with labels 7.391e+06, ..., 7.392e+06.

In [37]:
xds

<xarray.DataArray (band: 1, y: 1000, x: 1000)>
array([[[770. , 770. , ..., 792. , 792. ],
        [770. , 770. , ..., 792. , 792. ],
        ...,
        [766.5, 766.5, ..., 792.5, 792.5],
        [766. , 759.5, ..., 792.5, 792.5]]], dtype=float32)
Coordinates:
  * band         (band) int64 1
  * x            (x) float64 3.316e+05 3.316e+05 ... 3.321e+05 3.321e+05
  * y            (y) float64 7.392e+06 7.392e+06 ... 7.391e+06 7.391e+06
    spatial_ref  int64 0
Attributes:
    _FillValue:    0.0
    scale_factor:  1.0
    add_offset:    0.0

In [44]:
xds.expand_dims(['new_x', 'new_y'], axis=[3,4])

<xarray.DataArray (band: 1, y: 1000, x: 1000, new_x: 1, new_y: 1)>
array([[[[[770. ]],

         [[770. ]],

         [[770. ]],

         ...,

         [[792. ]],

         [[792. ]],

         [[792. ]]],


        [[[770. ]],

         [[770. ]],

         [[770. ]],
...
         [[792.5]],

         [[792.5]],

         [[792.5]]],


        [[[766. ]],

         [[759.5]],

         [[759.5]],

         ...,

         [[792. ]],

         [[792.5]],

         [[792.5]]]]], dtype=float32)
Coordinates:
  * band         (band) int64 1
  * x            (x) float64 3.316e+05 3.316e+05 ... 3.321e+05 3.321e+05
  * y            (y) float64 7.392e+06 7.392e+06 ... 7.391e+06 7.391e+06
    spatial_ref  int64 0
Dimensions without coordinates: new_x, new_y
Attributes:
    _FillValue:    0.0
    scale_factor:  1.0
    add_offset:    0.0