In [1]:
import svfpy
import rasterio
import numpy as np

In [2]:
mds = '../test/data/mds_sao_paulo_city_4000.tiff'

In [3]:
svf = svfpy.SVF(mds_path=mds, kernel_size=11)

In [4]:
profile = svf.mds_src.profile

In [5]:
# profile

In [6]:
windows = svfpy.calculate(svf)

rays ..


In [7]:
windows.shape

(4000, 4000, 11, 11)

In [8]:
fuse_lines = svfpy._fuse_lines(svf)

In [9]:
lines_mask = np.zeros((fuse_lines.shape[0], svf.kernel_size, svf.kernel_size), dtype='bool')
for k, fl in enumerate(fuse_lines):
    lm = np.zeros((svf.kernel_size, svf.kernel_size), dtype='bool')
    lm[fl[:, 0], fl[:, 1]] = True
    lines_mask[k] = lm
#     print(lm.astype('int'))
print(lines_mask[8].astype('int'))

[[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]


In [36]:
np.max(windows[np.tile(lines_mask[8], (4000, 4000,1,1))].reshape(4000,4000,6), axis=2)

array([[770.5, 770. , 770. , ..., 769. , 769. , 769. ],
       [770.5, 770.5, 770. , ..., 769. , 769. , 769. ],
       [770.5, 770.5, 770.5, ..., 769. , 769. , 769. ],
       ...,
       [762. , 762. , 762. , ..., 776. , 776. , 776. ],
       [762. , 762. , 762. , ..., 776. , 776. , 776. ],
       [762. , 762. , 762. , ..., 776. , 776. , 776. ]], dtype=float32)

In [ ]:
[m.shape for m in mdss]

[(4010, 4010),
 (2010, 2010),
 (1010, 1010),
 (510, 510),
 (260, 260),
 (135, 135),
 (73, 73),
 (42, 42),
 (26, 26),
 (18, 18),
 (14, 14)]

In [8]:
# mdss[-1].shape, transformations[-1]
mdss[-1]

array([[876.5, 905. ,   0. , 905. , 876.5, 862.5, 876.5, 905. ,   0. ,
        905. , 876.5, 862.5, 876.5, 905. ],
       [880. , 867. ,   0. , 867. , 880. , 853. , 880. , 867. ,   0. ,
        867. , 880. , 853. , 880. , 867. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
          0. ,   0. ,   0. ,   0. ,   0. ],
       [880. , 867. ,   0. , 867. , 880. , 853. , 880. , 867. ,   0. ,
        867. , 880. , 853. , 880. , 867. ],
       [876.5, 905. ,   0. , 905. , 876.5, 862.5, 876.5, 905. ,   0. ,
        905. , 876.5, 862.5, 876.5, 905. ],
       [899.5, 898.5,   0. , 898.5, 899.5, 879.5, 899.5, 898.5,   0. ,
        898.5, 899.5, 879.5, 899.5, 898.5],
       [876.5, 905. ,   0. , 905. , 876.5, 862.5, 876.5, 905. ,   0. ,
        905. , 876.5, 862.5, 876.5, 905. ],
       [880. , 867. ,   0. , 867. , 880. , 853. , 880. , 867. ,   0. ,
        867. , 880. , 853. , 880. , 867. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
         

In [9]:
# for k, m in enumerate(mdss):
#     transform = transformations[k]
#     profile.update(
#         transform=transform,
#         width=m.shape[0],
#         height=m.shape[1]
#     )

#     with rasterio.open(f'../tmp/raw-{k}-{m.shape[1]}.tif', 'w', **profile) as dst:
#         dst.write(m, 1)

In [10]:
svfpy._fuse_lines(svf).shape

(40, 6, 2)

In [11]:
svfpy._rays(svf)

AttributeError: 'SVF' object has no attribute 'view_as_windows'