In [1]:
import svfpy
# import rasterio
import numpy as np
from rioxarray import merge
from scipy import ndimage
# import os

In [2]:
mds = '../test/data/mds_sao_paulo_city_1000.tiff'
mds = '../data/raster/MDS_sampa-ZSTD.tif'

In [3]:
svf = svfpy.SVF(mds, '../tmp/', kernel_size_side=2500)

In [4]:
seila = svf.prepare_downscales()

Preparing Downscale, resolution of 0.5
Preparing Downscale, resolution of 1.0
Preparing Downscale, resolution of 2.0
Preparing Downscale, resolution of 3.0
Preparing Downscale, resolution of 5.0
Preparing Downscale, resolution of 15.5


In [7]:
k,m = svf.working_kernel(10,10,0.5)

In [8]:
m

array([[872.26, 872.35, 872.23, ..., 834.06, 833.93, 833.97],
       [872.33, 872.37, 872.23, ..., 834.04, 833.97, 833.87],
       [872.54, 872.45, 872.27, ..., 833.99, 834.03, 834.  ],
       ...,
       [784.71, 784.87, 784.73, ..., 781.43, 781.42, 781.56],
       [784.84, 784.87, 784.62, ..., 781.32, 781.33, 781.45],
       [784.71, 784.77, 784.51, ..., 781.12, 781.16, 781.43]],
      dtype=float32)

In [5]:
sum([(svf.kernels(r)[0] + 1) * (svf.kernels(r)[1] + 1)  for r in svf.resolutions])

3149

In [6]:
[svf.kernels(r)  for r in svf.resolutions]

[(58, 38), (29, 19), (14, 9), (9, 6), (5, 3), (1, 1)]

In [7]:
svf.svf()

2
0.0
11.25
22.5
33.75
45.0
56.25
67.5
78.75


In [8]:
svf.resolutions

array([ 0.5,  1. ,  2. ,  3. ,  5. , 15.5])

In [8]:
len(np.array([[r, t] for r in range(4) for t in svf.tangents]))

32

In [8]:
svf.downscales()

array([ 1.,  1.,  2.,  2.,  4.,  6., 10., 31.])

In [11]:
k_slice, mds = svf.working_kernel(1, 0,15.5)

1 1


In [12]:
9*1500, 10*1500, 6*1500,7*1500

(13500, 15000, 9000, 10500)

In [13]:
k_slice, mds.shape

(((1294, 697), (0, 1294)), (5523, 4390))

In [29]:
(1678-539-539)

600

In [25]:
svf.pad_max_by_resolution()

{0.5: 623, 1.0: 631, 2.0: 534, 3.0: 531, 5.0: 539, 15.5: 1087}

In [17]:
svf.kernels(5)

(6, 9)

In [19]:
svf.get_downscale(5).shape

(1, 14691, 9601)

In [31]:
np.all(np.isnan(mds))

False

In [32]:
mds

array([[   nan,    nan,    nan, ...,    nan,    nan,    nan],
       [   nan,    nan,    nan, ...,    nan,    nan,    nan],
       [   nan,    nan,    nan, ...,    nan,    nan,    nan],
       ...,
       [   nan,    nan,    nan, ..., 816.72, 816.6 , 816.7 ],
       [   nan,    nan,    nan, ..., 816.64, 816.65, 816.71],
       [   nan,    nan,    nan, ..., 816.75, 816.66, 816.72]],
      dtype=float32)

In [ ]:
merge.merge_arrays(d_scales, method='count')

<xarray.DataArray (band: 1, y: 1002, x: 1002)>
array([[[5., 5., 5., ..., 4., 0., 0.],
        [5., 5., 5., ..., 4., 0., 0.],
        [5., 5., 5., ..., 4., 0., 0.],
        ...,
        [4., 4., 4., ..., 4., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]], dtype=float32)
Coordinates:
  * x            (x) float64 3.316e+05 3.316e+05 ... 3.321e+05 3.321e+05
  * y            (y) float64 7.392e+06 7.392e+06 ... 7.391e+06 7.391e+06
  * band         (band) int64 1
    spatial_ref  int64 0
Attributes:
    _FillValue:    0.0
    scale_factor:  1.0
    add_offset:    0.0

In [ ]:
len(d_scales)

5

In [ ]:
svf = svfpy.SVF(mds_path=mds, kernel_size=15)

In [ ]:
profile = svf.mds_src.profile

In [ ]:
svf_result = svfpy.calculate(svf)
# points, points_sem_obs = svfpy.calculate(svf)

(0, 8)
Calculando arctan
(8, 12)
Calculando arctan
(12, 16)
Calculando arctan
(16, 20)
Calculando arctan
(20, 24)
Calculando arctan
(24, 28)
Calculando arctan
(28, 32)
Calculando arctan
(32, 36)
Calculando arctan
(36, 40)
Calculando arctan
Calulando max ...
Calculando SVF ..


In [ ]:
# np.sum(svf_result, axis=2).shape
# svfpy._fuse_lines(svf)
# svfpy.distance_matrix(size=17).shape

In [ ]:
with rasterio.open(f'../tmp/result.tif', 'w', **profile) as dst:
    dst.write(svf_result, 1)

In [ ]:
# for i in np.arange(40):
#     with rasterio.open(f'../tmp/result{i}.tif', 'w', **profile) as dst:
#         dst.write(result_temp[:,:,i,1], 1)

In [ ]:
Window.from_slices((0,30000), (0, 1024))

Window(col_off=0, row_off=0, width=1024, height=30000)

In [ ]:
for k, m in enumerate(mdss):
    # transform = transformations[k]
    m = np.mean(m[0:1000, 0:1000, :, :].reshape(1000,1000, 121), axis=2)
    profile.update(
        # transform=transform,
        # width=m.shape[0],
        # height=m.shape[1]
    )

    with rasterio.open(f'../tmp/11-11-{k}-{m.shape[1]}.tif', 'w', **profile) as dst:
        dst.write(m, 1)